language: rust
rust:
  - stable

language: python
matrix:
  include:
    - os: linux
      python: 2.7
      env:
        - TOXENV=py27
        - PYTHON_VERSION=2.7
    - os: linux
      python: 3.4
      env:
        - TOXENV=py34
        - PYTHON_VERSION=3.4
    - os: osx
      python: 2.7
      env:
        - TOXENV=py27
        - PYTHON_VERSION=2.7
    - os: osx
      python: 3.4
      env:
        - TOXENV=py34
        - PYTHON_VERSION=3.4
    - os: osx
      python: 3.5
      env:
        - TOXENV=py35
        - PYTHON_VERSION=3.5
    - os: osx
      python: 3.6
      env:
        - TOXENV=py36
        - PYTHON_VERSION=3.6

install:
  - pip install virtualenv
  - ./.travis/install.sh

script:
  - tox
  - ./.travis/publish.sh