[package]
name = "snips-nlu-utils"
version = "0.8.0-SNAPSHOT"
authors = ["Adrien Ball <adrien.ball@snips.ai>"]
edition = "2018"

[dependencies]
itertools = "0.7"
lazy_static = "0.2"
libc = "0.2"
regex = "0.2"
unicode-normalization = "0.1.5"
