[package]
name = "snips-nlu-utils-py"
version = "0.5.2"
authors = ["Adrien Ball <adrien.ball@snips.ai>"]

[lib]
name = "snisp_nlu_utils_py"
crate-type = ["cdylib"]

[dependencies]
snips-nlu-utils = { path = "../.."}
cpython = { version="0.1", default-features=false }
